version:
  '3.4'

networks:
  dockerapi-dev:
    driver: bridge


services:
  web-api:
    container_name: docker-testing-api
    image: api
    depends_on:
      - "app_db"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=app_db;Port=5432;Database=CarsXXX; IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dockerapi-dev
  
  app_db:
    container_name: app_db 
    image:
      postgres:latest
    ports:
      - "5433:5432"
    restart:
      always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "CarsXXX"
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dockerapi-dev
volumes: 
  app_data: